services:

  postgres-db:
    image: library/postgres:12
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: navstatus
      POSTGRES_USERNAME: postgres
      PGTZ: Europe/Oslo
      TZ: Europe/Oslo
    ports:
      - "3432:5432" # CATO: Changed to default port, for convenience.
    volumes:
      # Persist local test data across container reboots
      - pgdata:/var/lib/postgresql/data

  javabackend:
    build:
      context: .
    ports:
      - "3005:3005"
    environment:
      teamkatalogApiUrl: https://teamkatalog-api.intern.dev.nav.no
      swagger-api-key: key
      DB_USERNAME: postgres
      DB_PORT: 5432
      DB_HOST: postgres-db
      FRONTEND_LOCATION: 'placeholder'
      TENANT: trygdeetaten.no
      AZURE_APP_CLIENT_ID: foo
      AZURE_APP_CLIENT_SECRET: bar
      ENV: dev # TODO will be replaced by scope
      TZ: Europe/Oslo # CATO: Added for explicit time zone.
    depends_on:
      - postgres-db

  reactfrontend:
    build:
      context: ../statusplattform-frontend
      args:
        # Expecting this env var to be present, containing a token that:
        # - Is a GitHub PAT (classic)
        # - Has SSO access to navikt (or whichever other org your npm packages reside)
        NPM_AUTH_TOKEN: ${GITHUB_TOKEN} # CATO: I have an environment variable set to my GitHub Personal Access Token.
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BACKENDPATH: http://javabackend:3005
      ENV: local
      TZ: Europe/Oslo # CATO: Added for explicit time zone.
    depends_on:
      - javabackend

volumes:
  pgdata:
